### ISSUE TITLE
Cuda not available on any gpus other than 0

### ISSUE THREAD

**Issue by jeffsonyu** [SarahWeiii/diso#5]
I'm using the diso package, and it seems that it can't be put on any gpu device other than 0.
I'm simply using the following line:

```
device = "cuda:1"
diffmc = DiffMC(dtype=torch.float32).to(device) # or dtype=torch.float64
verts_diso, faces_diso = diffmc(sdf)  # or deform=None
```

The error seems like:
```
CUDA error 700: an illegal memory access was encountered (/tmp/pip-install-sw1umf14/diso_21b51e2d772f45e48cb953d19111a5ab/src/cumc.cu:673)
CUDA error 700: an illegal memory access was encountered (/tmp/pip-install-sw1umf14/diso_21b51e2d772f45e48cb953d19111a5ab/src/cumc.cu:679)
CUDA error 700: an illegal memory access was encountered (/tmp/pip-install-sw1umf14/diso_21b51e2d772f45e48cb953d19111a5ab/src/cumc.cu:680)
CUDA error 700: an illegal memory access was encountered (/tmp/pip-install-sw1umf14/diso_21b51e2d772f45e48cb953d19111a5ab/src/cumc.cu:692)
CUDA error 700: an illegal memory access was encountered (/tmp/pip-install-sw1umf14/diso_21b51e2d772f45e48cb953d19111a5ab/src/cumc.cu:721)
Traceback (most recent call last):
  File "test_data.py", line 54, in <module>
    verts_diso, faces_diso = diffmc(sdf)  # or deform=None
  File "/mnt/homes/zhenjun/miniconda3/envs/vtaco/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/homes/zhenjun/miniconda3/envs/vtaco/lib/python3.8/site-packages/diso/__init__.py", line 54, in forward
    verts, tris = self.func.apply(grid, deform, isovalue)
  File "/mnt/homes/zhenjun/miniconda3/envs/vtaco/lib/python3.8/site-packages/diso/__init__.py", line 22, in forward
    verts, tris = mc.forward(grid, isovalue)
RuntimeError: The specified pointer resides on host memory and is not registered with any CUDA device.
```
There won't be any problem if I set `device = "cuda:0"`, and the same issue occured on `DiffDMC`.
Could you help me with this? Really appreciate it!

**Comment by jeffsonyu** [comment]
Hi! For your example, I still can't run with **device = "cuda:1"**, and the error remains the same as I mentioned above. Dose that mean this is the problem with my device?

**Comment by jeffsonyu** [comment]
I've also tried **CUDA_VISIBLE_DEVICES**, and it works with device=cuda:0 while CUDA_VISIBLE_DEVICES = "1". There won't be any problem for me but I'm still confused why your example seems right on your device but not on mine...

**Comment by SarahWeiii** [comment]
Hi I think it is because different GPU types have different ways to deal with cuda devices in C++. I have manually added a global cuda device now, you can try if it fixes the problem.

**Comment by jeffsonyu** [comment]
Thanks! Does this mean I have to install and build your package from this repo, or has it been updated on the pypi package?

**Comment by SarahWeiii** [comment]
Thank you for the reminder. I have updated the pypi package as well now.
